site:
  title: ThoughtSpot Demo Site
  url: https://docs.thoughtspot.com/thoughtspot-docs
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
    branches: ['6.0', '6.1', '6.2', '6.3']
    start_path: software/
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: build/ui-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true

output:
  clean: true
  dir: docs
runtime:
  fetch: true
